services:
  mysql:
    image: mysql:8.4
    container_name: psoft-mysql
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: lib
      MYSQL_PASSWORD: lib
      MYSQL_ROOT_PASSWORD: root
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-plib", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: psoft-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  mysql_data:
